name: ShellCheck

on:
  push:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: ShellCheck
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
